In [ ]:
# 넘파이의 필요성
# 파이썬의 리스트는 연산 전용이 아니므로 계산을 수행하기 어렵습니다.
l1 = [1,2,3,4]
l2 = [1,1,1,1]

print(l1 + l2)

In [ ]:
# 원소별 덧셈
l1 = [1,2,3,4]
l2 = [1,1,1,1]

result = []
for x, y in zip(l1, l2):
    result.append(x + y)

print(result)

In [ ]:
# 중첩 리스트의 경우, 상당히 복잡해집니다.

l3 = [[1,2,3],[4,5,6]]
l4 = [[1,1,1],[1,1,1]]

result = []  
for i in range(len(l3)):
    temp = []
    for j in range(len(l3[i])):
        temp.append(l3[i][j] + l4[i][j])
    result.append(temp)

print(result)

In [ ]:
# 파이썬의 리스트를 사용한 연산의 가장 큰 문제점은 연산 속도가 매우 느립니다.
# 이는 파이썬은 인터프리터에 의해 해석되어 실행되기 때문입니다.

# 넘파이는 파이썬의 리스트 대신 ndarray(n-dimetional array, 다차원 배열)라는 클래스, 즉 다차원배열을 제공합니다.
# 다차원 배열은 연산에 최적화되어 있어 계산을 좀 더 편리하게 할 수 있습니다. 그리고 일부 구현이 C언어로 작성되어 있어 연산이
# 매우 빠르고 메모리에 대한 최적화도 되어 있습니다.

In [ ]:
import numpy as np # 관례적으로 np라는 별칭을 사용합니다.

In [ ]:
# 파이썬의 리스트 사용
a = np.array([1, 2, 3, 4])
print(a)

In [ ]:
# 파이썬의 튜플 사용
a = np.array((1, 2, 3, 4))
print(a)

In [ ]:
# 파이썬의 리스트와 마찬가지로 인덱싱을 제공함

#              -4 -3 -2 -1
#               0  1  2  3
arr = np.array([1, 2, 3, 4])
print(arr[0], arr[1], arr[2], arr[3])
print(arr[-1], arr[-2], arr[-3], arr[-4]) 

# 존재하지 않는 원소에 대하여 인덱싱을 수행하면 오류가 발생합니다.
# print(arr[10])
# print(arr[-10])

In [ ]:
# 다차원 배열은 반복문에도 사용될 수 있습니다.
arr = np.array([1, 2, 3, 4])
for i in arr:
    print(i, end=" ")

In [ ]:
# 다차원 배열이므로 2차원 배열도 생성할 수 있습니다.
# 2차원 배열은 파이썬의 중첩 리스트를 사용하여 생성합니다.
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

In [ ]:
# 2차원 배열에 대하여 인덱싱은 기존 파이썬과 조금 다르게 튜플을 사용합니다.
l = [[1,2,3], [4,5,6]]
print(l[1][2])

#             -3 -2 -1
#              0  1  2
a = np.array([[1, 2, 3],  # 0  -2
              [4, 5, 6]]) # 1  -1
print(a[1,2])
print(a[-2, -3])

In [ ]:
# 3차원 배열도 생성할 수 있습니다.
arr = np.array([[[1,2],
                 [3,4]],
                [[5,6],
                 [7,8]]])
print(arr)

In [2]:
import numpy as np

# 생성과 초기화
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [3]:
# zeros: 원소가 0인 배열을 생성하는 함수

# 1차원 배열 생성
arr = np.zeros(10) # 원소는 실수(부동소수점) 타입으로 생성됩니다.
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
arr = np.zeros(10, dtype=np.int) # 원소의 타입을 설정하려면 dtype 매개변수에 np.int라고 설정해 주시면 됩니다.
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [5]:
# 2차원 배열
arr = np.zeros((2,3)) # 튜플 형태로 전달해야 합니다.
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# 3차원 배열
arr = np.zeros((2,3,4)) # 면, 행, 열
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [7]:
# ones: 원소가 1인 배열을 생성하는 함수
print(np.ones(5), "\n")
print(np.ones((2,3)), "\n")
print(np.ones((2,3,4)))

[1. 1. 1. 1. 1.] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [8]:
# full: 특정 값을 사용하여 배열을 생성하는 함수
print(np.full(5, 3.14), "\n")
print(np.full((2,3), 3.14), "\n")
print(np.full((2,3,4), 3.14))

[3.14 3.14 3.14 3.14 3.14] 

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]] 

[[[3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]]

 [[3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]]]


In [9]:
# eye: 단위 행렬을 생성하는 함수
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
# tri: 삼각 행렬을 생성하는 함수
print(np.tri(5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 인자로 전달된 배열과 동일 형상의 배열을 생성하는 함수도 제공합니다.
# zeros_like
# ones_like
# full_like

In [11]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3],
               [4,5,6]])
print(np.zeros_like(a1), "\n")
print(np.zeros_like(a2))

[0 0 0 0 0] 

[[0 0 0]
 [0 0 0]]


In [12]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3],
               [4,5,6]])
print(np.ones_like(a1), "\n")
print(np.ones_like(a2)) 


[1 1 1 1 1] 

[[1 1 1]
 [1 1 1]]


In [13]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3],
               [4,5,6]])
print(np.full_like(a1, 9), "\n")
print(np.full_like(a2, 9))

[9 9 9 9 9] 

[[9 9 9]
 [9 9 9]]


In [14]:
# 정수 범위로 배열을 생성
print(np.array(range(1,10,2)))

# arange(start, stop, step)
# range와 마찬가지로 반개구간입니다. [start, stop)
print(np.arange(1,10,2))

[1 3 5 7 9]
[1 3 5 7 9]


In [15]:
print(np.arange(0,10,1))

[0 1 2 3 4 5 6 7 8 9]


In [16]:
print(np.arange(0,10)) # step의 기본값은 1입니다.
print(np.arange(10))   # start의 기본값은 0입니다.

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [17]:
# 범위 내에서 균등 간격으로 배열을 생성
arr = np.linspace(-3, 3, 5)
print(arr)

[-3.  -1.5  0.   1.5  3. ]


In [18]:
# 임의의 값으로 배열 생성할 수 있습니다.
# 난수 발생 범위는 0이상 1미만입니다.
print(np.random.random(3), "\n")
print(np.random.random((2,3)), "\n")
print(np.random.random((2,3,4)))

[0.75102131 0.34873733 0.21546312] 

[[0.9303118  0.91914342 0.99058249]
 [0.70701454 0.23970566 0.27354149]] 

[[[0.39761207 0.08461749 0.40796167 0.2359954 ]
  [0.72661169 0.11727734 0.26265051 0.42489036]
  [0.87982853 0.68428963 0.18208337 0.22850839]]

 [[0.33038346 0.71807788 0.74928507 0.29356149]
  [0.71118221 0.5803654  0.51598126 0.48663666]
  [0.45906153 0.51131514 0.76522861 0.42518043]]]


In [34]:
# 일정 범위 내에서 정수형 난수를 생성
# 범위는 반개구간입니다.
arr = np.random.randint(0, 10, (3,3))
print(arr)

[[0 3 3]
 [3 9 9]
 [4 0 3]]


In [46]:
# 정규 분표(nomal distribution)를 고려한 난수 배열 생성
# normal(평균, 표준편차, 모양)
arr = np.random.normal(0, 1, (3,3))
print(arr)

[[ 1.70284341 -0.57149586 -0.7811666 ]
 [ 0.37232644  1.03078533 -1.90119569]
 [-0.5415339   1.02245399 -0.07053306]]
