In [1]:
import numpy as np
import tensorflow as tf # 관례적으로 tf라는 별칭을 사용합니다.

In [ ]:
# 케라스의 기반이 되는 텐서플로는 넘파이(NumPy)의 다차원 배열과 유사한 텐서 프레임워크을 제공합니다.
# 넘파이의 다차원 배열과 텐서플로의 텐서의 차이
# 1. 텐서플로는 GPU와 TPU 같은 하드웨어 가속기를 사용할 수 있습니다.
# 2. 텐서플로는 임의의 미분 가능 텐서 표현의 그레이디언트를 자동으로 계산합니다.
# 3. 텐서플로 계산은 단일 머신에 있는 여러 개의 장치나 머신에 분산할 수 있습니다.

In [2]:
# 1. 텐서의 종류와 생성
# 1-1. 0차원 텐서
# 하나의 숫자만을 저장하고 있는 텐서로 스칼라(scalar)라고도 합니다.
x = tf.constant(1)
print(x)

tf.Tensor(1, shape=(), dtype=int32)


In [3]:
# 1-2. 1차원 텐서
# 숫자를 가진 1차원 배열로 벡터(vector)라고도 합니다.
# 다차원 배열과 마찬가지로 하나의 축(열)을 가집니다.
x = tf.constant([1,2,3,4]) # 파이썬의 리스트를 사용하여 생성할 수 있습니다.
print(x)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [4]:
# 1-3. 2차원 텐서
# 1차원 텐서를 원소로 하는 텐서로 벡터의 배열 또는 행렬(matrix)라고도 합니다.
# 다차원 배열과 마찬가지로 2개의 축(행과 열)을 가집니다.
x = tf.constant([[1,2,3],
                 [4,5,6],
                 [7,8,9]])  # 파이썬의 리스트를 사용하여 생성할 수 있습니다.
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [5]:
# 1-4. 3차원 텐서
# 2차원 텐서를 원소로 하는 텐서입니다. 3차원 이상의 텐서는 이를 지칭할 용어가 없어 그냥
# 3차원 텐서라고 합니다.
x = tf.constant([[[1,2],
                  [3,4]],
                 [[5,6],
                  [7,8]]])  # 파이썬의 리스트를 사용하여 생성할 수 있습니다.
print(x)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [6]:
# 2. 텐서의 속성
x = tf.constant([[1,2,3],
                 [4,5,6]])

print(x.ndim) # 차원 또는 축의 갯수

2


In [7]:
print(x.shape) # 형상 정보로 튜플로 표현합니다.

(2, 3)


In [8]:
print(x.dtype) # 원소 또는 요소의 타입 정보

<dtype: 'int32'>


In [ ]:
# 3. 텐서의 다양한 생성 방법

In [9]:
# 3-1. 파이썬의 리스트를 사용
l1 = [1, 2, 3, 4]
print(tf.constant(l1), "\n")

l2 = [[1, 2],
      [3, 4]]
print(tf.constant(l2), "\n")

l3 = [[[1, 2],
       [3, 4]],
      [[5, 6],
       [7, 8]]]
print(tf.constant(l3))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [10]:
# 참고! 텐서 생성 시, 파이썬이 제공하는 다양한 타입을 저장할 수 있습니다.
# 그러나 텐서는 범용 컨테이너가 아닌 수치 연산 전용 컨테이너므로 아래와 같이 서로 다른 타입이
# 전달될 경우, 데이터의 손실이 없는 연산 가능한 공통의 타입으로 암시적 변환이 이루어집니다.
x = tf.constant([10, 3.14, True])
print(x)

tf.Tensor([10.    3.14  1.  ], shape=(3,), dtype=float32)


In [11]:
# 따라서 수치 데이터로 변환할 수 없는 데이터가 포함될 경우, 오류가 발생합니다.
y = tf.constant([10, 3.14, True, "hello"])
print(y)

ValueError: Can't convert Python sequence with mixed types to Tensor.

In [14]:
# 텐서 생성 시, 원소의 타입을 명시적으로 지정할 수 있습니다.
t1 = tf.constant([1,2,3,4], dtype=tf.float32)
print(t1)

t2 = tf.constant([10, 3.14, True], dtype=tf.float32)
print(t2)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor([10.    3.14  1.  ], shape=(3,), dtype=float32)


In [15]:
# 3-2. 넘파이의 다차원을 사용
a1 = np.array([1, 2, 3, 4])
print(tf.constant(a1), "\n")

a2 = np.array([[1, 2],
               [3, 4]])
print(tf.constant(a2), "\n")

a3 = np.array([[[1, 2],
                [3, 4]],
               [[5, 6],
                [7, 8]]])
print(tf.constant(a3))


tf.Tensor([1 2 3 4], shape=(4,), dtype=int64) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64) 

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int64)


In [16]:
# 참고! 텐서를 다차원 배열로 변환할 수 있습니다.
t = tf.constant([1, 1, 1, 1, 1])
print("t:", t)

a = t.numpy()
print("a:", a)

t: tf.Tensor([1 1 1 1 1], shape=(5,), dtype=int32)
a: [1 1 1 1 1]


In [17]:
# 3. 텐서플로 API의 사용

# 3-1. zeros: 모든 원소가 0인 텐서를 생성하는 함수

# 형상 정보를 튜플 또는 리스트로 전달합니다.
print(tf.zeros((3,)))
print(tf.zeros([3]))
print(tf.zeros(3))     # 1차원 텐서의 경우, 튜플이 아닌 값을 사용할 수 있습니다.

print(tf.zeros((2,3)))
print(tf.zeros((2,2,3)))

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


In [18]:
print(tf.zeros(3, dtype=tf.int32)) # 타입을 명시적으로 지정할 수 있습니다.

tf.Tensor([0 0 0], shape=(3,), dtype=int32)


In [19]:
# 3-2. ones: 모든 원소가 1인 텐서를 생성하는 함수
print(tf.ones((3,)))
print(tf.ones([3]))
print(tf.ones(3)) # 1차원 텐서의 경우, 튜플이 아닌 값을 사용할 수 있습니다.

print(tf.ones((2,3)))
print(tf.ones((2,2,3)))

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


In [20]:
print(tf.ones(3, dtype=tf.int32)) # 타입을 명시적으로 지정할 수 있습니다.

tf.Tensor([1 1 1], shape=(3,), dtype=int32)


In [21]:
# 3-3. fill: 특정 값을 사용하여 텐서를 생성하는 함수
print(tf.fill((3,), 9))
print(tf.fill([3], 9))
print(tf.fill(3, 9)) # 1차원 텐서의 경우, 튜플이 아닌 값을 사용할 수 있습니다.

print(tf.fill((2,3), 9))
print(tf.fill((2,2,3), 9))

tf.Tensor([9 9 9], shape=(3,), dtype=int32)
tf.Tensor([9 9 9], shape=(3,), dtype=int32)
tf.Tensor([9 9 9], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]], shape=(2, 2, 3), dtype=int32)


In [22]:
print(tf.fill((2,3), 9, dtype=tf.float32)) # 타입을 명시적으로 지정할 수 없습니다.

TypeError: fill() got an unexpected keyword argument 'dtype'

In [23]:
# 3-4. 기존 텐서의 형상을 사용하여 텐서를 생성할 수 있습니다.
t = tf.zeros((2,3))
print(tf.zeros_like(t), "\n")
print(tf.ones_like(t), "\n")
# fill_like는 제공하지 않습니다.

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32) 

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32) 



In [24]:
# 3-5. 난수를 사용하여 텐서를 생성할 수 있습니다.
print(tf.random.normal(shape=(3,), mean=0, stddev=1))

tf.Tensor([-1.3810233  -0.38968164  0.40601113], shape=(3,), dtype=float32)


In [25]:
# 4. 기타

# tf.range(start, limit=None, delta=1)
print(tf.range(1,10,2))
print(tf.range(1,10,0.5))

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5], shape=(18,), dtype=float32)


In [26]:
# tf.linspace(start, stop, num, name=None)
print(tf.linspace(-3, 3, 5))

tf.Tensor([-3.  -1.5  0.   1.5  3. ], shape=(5,), dtype=float64)
