In [1]:
import numpy as np

# 배열의 속성 조회
arr = np.array([1,2,3])

print(arr.ndim)  # 차원 정보
print(arr.shape) # 형상 정보
print(arr.dtype) # 원소의 타입 정보
print(arr.size)  # 원소의 갯수

1
(3,)
int64
3


In [2]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

2
(2, 3)
int64
6


In [5]:
# 배열의 원소 조회 1. 인덱싱(indexing)

#              -4 -3 -2 -1
#               0  1  2  3
arr = np.array([1, 2, 3, 4])
print(arr[0], arr[1], arr[2], arr[3])
print(arr[-1], arr[-2], arr[-3], arr[-4])  

# print(arr[5]) # ERROR
# print(arr[-5]) # ERROR

1 2 3 4
4 3 2 1


IndexError: index -5 is out of bounds for axis 0 with size 4

In [6]:
# 인덱싱을 사용한 원소의 수정
arr[0] = 0
arr[1] = 0
arr[2] = 0
arr[3] = 0
print(arr)

[0 0 0 0]


In [7]:
# 배열의 원소 조회 2. 슬라이싱(slicing)
# 사용방법: 배열명[시작인덱스:마지막인덱스:간격] -> 반개구간: [시작인덱스,마지막인덱스)
arr = np.array([11, 22, 33, 44, 55, 66])

print(arr[0:6:1])

[11 22 33 44 55 66]


In [8]:
print(arr[0:6]) # 간격의 기본 값은 1입니다.
print(arr[0:])  # 마지막 인덱스의 기본값은 '마지막인덱스+1'입니다.
print(arr[:])   # 시작 인덱스의 기본값은 0입니다.

[11 22 33 44 55 66]
[11 22 33 44 55 66]
[11 22 33 44 55 66]


In [9]:
# 슬라이싱시, 음수도 사용할 수 있습니다.
print(arr[-6::2])
print(arr[5:2:-1])
print(arr[2:-1])

[11 33 55]
[66 55 44]
[33 44 55]


In [10]:
# 배열 전체에 대하여 간격을 음수로 사용하면 역순으로 선택됩니다.
print(arr[::-1])

     0   1   2   3   4   5
#  [11, 22, 33, 44, 55, 66]
print(arr[::-2])

[66 55 44 33 22 11]
[66 44 22]


In [11]:
# 파이썬의 리스트와 다른 점은 슬라이싱 후에 반환된 배열은 복사본이 아니라 뷰입니다.
# 따라서 반환된 배열에 대하여 수정할 경우, 원본에 반영이 됩니다. 이는 성능을 높이고 메모리 이슈를 피하기 위해서 입니다.
l = [11, 22, 33, 44, 55]
x = l[:]
x[0] = 0
print(l)

[11, 22, 33, 44, 55]


In [12]:
a = np.array([11, 22, 33, 44, 55])
x = a[:]
x[0] = 0
print(a)

[ 0 22 33 44 55]


In [13]:
a = np.array([11, 22, 33, 44, 55])
x = a[1:4]
x[0] = 0
print(a)

[11  0 33 44 55]


In [14]:
# 복사본을 사용하고 싶다면 copy 메서드를 사용하면 됩니다.
a = np.array([11, 22, 33, 44, 55])
x = a[:].copy()
x[0] = 0
print(a)

[11 22 33 44 55]


In [15]:
# 슬라이싱을 사용하여 일부 구간을 수정할 수 있습니다.
arr = np.array([1,2,3,4,5,6])
arr[::2] = 0
print(arr)

[0 2 0 4 0 6]


In [16]:
# 2차원 배열에 대해서도 슬라이싱을 할 수 있습니다.
#                 0   1   2   3   4
arr = np.array([[ 1,  2,  3,  4,  5],  # 0
                [ 6,  7,  8,  9, 10],  # 1
                [11, 12, 13, 14, 15],  # 2
                [16, 17, 18, 19, 20]]) # 3

print(arr[0:4:1, 0:5:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
print(arr[::,::]) 
print(arr[:,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
print(arr[0:3,1:4])

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [19]:
print(arr[2:, ::-1])

[[15 14 13 12 11]
 [20 19 18 17 16]]


In [20]:
print(arr[::-1, ::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [21]:
# 인덱싱과 슬라이싱을 조합할 수 있습니다.
arr = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

print(arr[0, ::2])

[1 3 5]


In [22]:
# 배열의 원소 조회 3. 팬시 인덱싱(fancy indexing)
# 다수의 인덱스를 사용하여 원소를 조회하는 방법
arr = np.array([10, 20, 30, 40, 50, 60])

print(np.array([arr[0], arr[2]]))

[10 30]


In [23]:
idx = np.array([0, 2])
print(arr[idx])

[10 30]


In [24]:
idx = np.array([[0,1], [3,2]])
print(arr[idx])

[[10 20]
 [40 30]]


In [25]:
# 2차원 배열도 팬시 인덱싱이 가능합니다.
#                0 1 2
arr = np.array([[1,2,3],  # 0
                [4,5,6],  # 1
                [7,8,9]]) # 2

# (0,0), (0,2), (2,0), (2,2)

rows = np.array([0, 0, 2, 2])
cols = np.array([0, 2, 0, 2])
print(arr[rows, cols])

[1 3 7 9]


In [26]:
arr[rows, cols] = 0
print(arr)

[[0 2 0]
 [4 5 6]
 [0 8 0]]


In [27]:
# 팬시 인덱싱과 인덱싱 그리고 슬라이싱을 조합할 수 있습니다.

#                0 1 2
arr = np.array([[1,2,3],  # 0
                [4,5,6],  # 1
                [7,8,9]]) # 2

rows = np.array([0,1])
cols = np.array([1,2])

print(arr[0, cols]) # [2, 3]
print(arr[rows, 0]) # [1, 4]

[2 3]
[1 4]


In [28]:
print(arr[rows, :])
print(arr[:,cols])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]


In [30]:
# 배열의 원소 조회 4. 불리언 인덱싱(boolean indexing)
# 배열의 각 요소에 대하여 True를 사용하여 선택하는 기능

arr = np.array([1,2,3,4,5])
bools = np.array([True, False, True, False, True])
print(arr[bools])

[1 3 5]


In [31]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

bools = np.array([[True, False, True],
                  [False, False, False],
                  [True, False, True]])
print(arr[bools])

[1 3 7 9]


In [32]:
arr[bools] = 0
print(arr)

[[0 2 0]
 [4 5 6]
 [0 8 0]]
