In [3]:
import numpy as np
import tensorflow as tf

# 텐서의 조회

# 1. 인덱싱(indexing)
#                 -5  -4  -3  -2  -1
#                  0   1   2   3   4
t1 = tf.constant([11, 22, 33, 44, 55])

print(t1[0])
print(t1[4])

print(t1[-1])
print(t1[-5])

# print(t1[10]) # 존재하지 않는 원소에 대한 인덱싱은 오류입니다.
print(t1[-10]) # 존재하지 않는 원소에 대한 인덱싱은 오류입니다.

tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)


InvalidArgumentError: slice index -5 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

In [4]:
t2 = tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(t2[0,0])
print(t2[2,2])
print(t2[-1,-1])
print(t2[-3,-3])

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [5]:
# 2. 슬라이싱(slicing)
#                  0   1   2   3   4   5   6
#                 -7  -6  -5  -4  -3  -2  -1
t1 = tf.constant([11, 22, 33, 44, 55, 66, 77])

print(t1[1:6:2])

tf.Tensor([22 44 66], shape=(3,), dtype=int32)


In [6]:
print(t1[0:7:1])
print(t1[0:7])
print(t1[0:])
print(t1[:])

tf.Tensor([11 22 33 44 55 66 77], shape=(7,), dtype=int32)
tf.Tensor([11 22 33 44 55 66 77], shape=(7,), dtype=int32)
tf.Tensor([11 22 33 44 55 66 77], shape=(7,), dtype=int32)
tf.Tensor([11 22 33 44 55 66 77], shape=(7,), dtype=int32)


In [7]:
print(t1[::2])
print(t1[::-1])
print(t1[::-2])

tf.Tensor([11 33 55 77], shape=(4,), dtype=int32)
tf.Tensor([77 66 55 44 33 22 11], shape=(7,), dtype=int32)
tf.Tensor([77 55 33 11], shape=(4,), dtype=int32)


In [8]:
# 2차원 텐서에 대한 슬라이싱
t2 = tf.constant([[0,1,2,3],
                  [4,5,6,7],
                  [8,9,0,1]])
print(t2[::2,::2], "\n")
print(t2[::-1, ::-1])

tf.Tensor(
[[0 2]
 [8 0]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 0 9 8]
 [7 6 5 4]
 [3 2 1 0]], shape=(3, 4), dtype=int32)


In [9]:
# 텐서의 형상 변경
# 텐서플로는 텐서의 형상을 변경할 수 있도록 reshape 함수를 제공합니다.
t1 = tf.range(9)
print(t1)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [10]:
print(tf.reshape(t1, (3,3)))

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [11]:
# 주의할 점은 형상을 변경하기 전과 후의 텐서에 대하여 원소의 갯수가 동일해야 합니다.
print(tf.reshape(t1, (3,4)))  # 오류입니다.

InvalidArgumentError: Input to reshape is a tensor with 9 values, but the requested shape has 12 [Op:Reshape]

In [12]:
print(tf.reshape(t1, (1, -1))) # 1 x ? = 9

tf.Tensor([[0 1 2 3 4 5 6 7 8]], shape=(1, 9), dtype=int32)


In [13]:
print(tf.reshape(t1, (-1, 1))) # ? x 1 = 9

tf.Tensor(
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]], shape=(9, 1), dtype=int32)


In [15]:
# 텐서를 평평하게 만들 수 있습니다.
print(np.zeros((3,3)).reshape(-1))

t1 = tf.constant([[1,2,3],
                  [4,5,6]])
print(tf.reshape(t1, (-1,))) 

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
