In [1]:
import numpy as np

# 1. 전치(transposed)
# 주 대각선을 축으로 하는 반사 대칭을 가하여 변환을 수행합니다.
arr = np.tri(4, dtype=np.int)
print(arr)

[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]


In [2]:
x = arr.T
print(x)

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


In [3]:
# 전치된 결과는 복사본이 아니라 원본에 대한 뷰입니다.
x[:] = 0
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [4]:
# 2. 재구조화(reshape)
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [5]:
x = arr.reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# 새로운 형상으로 반환된 배열 역시 복사본이 아닌 원본에 대한 뷰입니다.
x[:] = 0
print(arr)

[0 0 0 0 0 0 0 0 0]


In [7]:
# 현재 배열이 원본인지 아니면 원본에 대한 뷰인지를 확인하려면 base 속성을 확인하면 됩니다.
print(x.base)
print(arr.base)

[0 0 0 0 0 0 0 0 0]
None


In [8]:
# 주의! 변환 전의 원소의 갯수와 변환 후의 원소의 갯수가 일치하지 않으면 오류가 발생합니다.
arr = np.arange(1,10)
print(arr.size)

x = arr.reshape(2,3)

9


ValueError: cannot reshape array of size 9 into shape (2,3)

In [9]:
# reshape 사용 시, 행 또는 열에 -1을 전달할 수 있습니다.
# 이것의 의미는 -1이 전달된 차원은 남은 차원의 정보로 계산하겠다는 의미입니다.
arr = np.arange(1,10)
print(arr.size, arr) # 9

9 [1 2 3 4 5 6 7 8 9]


In [10]:
print(arr.reshape(-1, 1)) # ? x 1 = 9

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [11]:
print(arr.reshape(1, -1)) # 1 x ? = 9

[[1 2 3 4 5 6 7 8 9]]


In [12]:
arr = np.arange(10)
print(arr.size, arr)

10 [0 1 2 3 4 5 6 7 8 9]


In [13]:
print(arr.reshape(-1, 5)) # ? x 5 = 10

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
print(arr.reshape(2, -1)) # 2 x ? = 10

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
# 주의! -1를 사용할 때도 변환 전과 후의 원소의 갯수가 일치해야 합니다.
arr = np.arange(1,10)
print(arr.size, arr)

9 [1 2 3 4 5 6 7 8 9]


In [17]:
print(arr.reshape(-1, 4)) # ? x 4 = 9

ValueError: cannot reshape array of size 9 into shape (4)

In [18]:
print(arr.reshape(-1,-1)) # ? x ? = 

ValueError: can only specify one unknown dimension

In [ ]:
# 축의 개념
# 다차원 배열의 구조를 변경하거나 연산을 수행하는 기준으로 사용됩니다.
# 1차원 배열: 0축(열)
# 2차원 배열: 0축(행), 1축(열)
# 3차원 배열: 0축(면), 1축(행), 2축(열)

In [19]:
# 삽입
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
# 1번째 행에 삽입합니다. 삽입을 수행하면 새로운 배열이 반환됩니다.
print(np.insert(arr,
                1, # 위치
                0, # 값
                axis=0)) # 축 정보

[[1 2 3]
 [0 0 0]
 [4 5 6]
 [7 8 9]]


In [21]:
# 1번째 열에 삽입합니다.
print(np.insert(arr,
                1,
                0,
                axis=1))

[[1 0 2 3]
 [4 0 5 6]
 [7 0 8 9]]
