In [1]:
# 텐서의 연산
import numpy as np
import tensorflow as tf

# 1. 산술 연산
# 0차원 텐서(스칼라)의 연산
a = tf.constant(3)
b = tf.constant(2)

print(tf.add(a, b))

tf.Tensor(5, shape=(), dtype=int32)


In [2]:
# 산술 연산자를 사용할 수 있습니다.
print(a + b) 
print(a - b) 
print(a * b) 
print(a / b) 
print(a // b)
print(a % b) 
print(a ** b)
print(-a)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(1.5, shape=(), dtype=float64)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(-3, shape=(), dtype=int32)


In [3]:
# 1차원 텐서(벡터)의 연산
a = tf.constant([11,22,33,44])
b = tf.constant([2,2,2,2])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

tf.Tensor([13 24 35 46], shape=(4,), dtype=int32)
tf.Tensor([ 9 20 31 42], shape=(4,), dtype=int32)
tf.Tensor([22 44 66 88], shape=(4,), dtype=int32)
tf.Tensor([ 5.5 11.  16.5 22. ], shape=(4,), dtype=float64)
tf.Tensor([ 5 11 16 22], shape=(4,), dtype=int32)
tf.Tensor([1 0 1 0], shape=(4,), dtype=int32)
tf.Tensor([ 121  484 1089 1936], shape=(4,), dtype=int32)


In [4]:
# 2차원 텐서(행렬)의 연산
a = tf.constant([[11,22],
                 [33,44]])
b = tf.constant([[2,2],
                 [2,2]])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

tf.Tensor(
[[13 24]
 [35 46]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 9 20]
 [31 42]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[22 44]
 [66 88]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5.5 11. ]
 [16.5 22. ]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[ 5 11]
 [16 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 0]
 [1 0]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 121  484]
 [1089 1936]], shape=(2, 2), dtype=int32)


In [5]:
# 2. 브로드캐스팅
print(tf.range(3)+ 5)

tf.Tensor([5 6 7], shape=(3,), dtype=int32)


In [6]:
print(tf.ones((3,3), dtype=tf.int32) + tf.range(3))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [7]:
print(tf.reshape(tf.range(3, dtype=tf.int32), shape=(3, 1)) + tf.range(3))

tf.Tensor(
[[0 1 2]
 [1 2 3]
 [2 3 4]], shape=(3, 3), dtype=int32)


In [8]:
# 3. 행렬곱
x = tf.constant([[1,2,3],
                 [4,5,6]])
y = tf.constant([[10,11],
                 [20,21],
                 [30,31]])

print(tf.matmul(x, y)) # x(2,3), y(3,2)
print(x @ y)

tf.Tensor(
[[140 146]
 [320 335]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[140 146]
 [320 335]], shape=(2, 2), dtype=int32)


In [9]:
z = tf.constant([[1,1],
                 [1,1]])
print(x @ z) # x(2,3) @ z(2,2)

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,3], In[1]: [2,2] [Op:MatMul]

In [10]:
# 4. 연산 함수
# 1. reduce_sum: 넘파이의 sum함수와 유사한 함수
arr = np.arange(1, 9+1).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(np.sum(arr, axis=None))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

45
[12 15 18]
[ 6 15 24]


In [12]:
t = tf.reshape(tf.range(1,10), (3,3))
print(t)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [13]:
print(tf.reduce_sum(t, axis=None))
print(tf.reduce_sum(t, axis=0))
print(tf.reduce_sum(t, axis=1))

tf.Tensor(45, shape=(), dtype=int32)
tf.Tensor([12 15 18], shape=(3,), dtype=int32)
tf.Tensor([ 6 15 24], shape=(3,), dtype=int32)


In [14]:
# reduce_mean: 넘파이의 mean 함수와 유사한 함수
arr = np.arange(1, 9+1).reshape(3, 3)
print(arr)
print(np.mean(arr, axis=None))
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
[4. 5. 6.]
[2. 5. 8.]


In [15]:
t = tf.reshape(tf.range(1,10), (3,3))
print(t)
print(tf.reduce_mean(t, axis=None))
print(tf.reduce_mean(t, axis=0))
print(tf.reduce_mean(t, axis=1))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([2 5 8], shape=(3,), dtype=int32)


In [16]:
# reduce_min: 넘파이의 min 함수와 유사한 함수
arr = np.arange(1, 9+1).reshape(3, 3)
print(arr)
print(np.min(arr, axis=None))
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[1 2 3]
[1 4 7]


In [17]:
t = tf.reshape(tf.range(1,10), (3,3))
print(t)
print(tf.reduce_min(t, axis=None))
print(tf.reduce_min(t, axis=0))
print(tf.reduce_min(t, axis=1))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 4 7], shape=(3,), dtype=int32)


In [ ]:
# reduce_max: 넘파이의 max와 유사한 함수

In [18]:
# argmin: 넘파이의 argmin과 유사한 함수
arr = np.arange(1, 9+1).reshape(3, 3)
print(arr)
print(np.argmin(arr, axis=None))
print(np.argmin(arr, axis=0))
print(np.argmin(arr, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0
[0 0 0]
[0 0 0]


In [19]:
t = tf.constant([[2,5,9],
                 [3,0,4],
                 [1,7,6]])
print(t)
# axis의 기본값은 0입니다.
print(tf.argmin(t, axis=0)) 
print(tf.argmin(t, axis=1))

tf.Tensor(
[[2 5 9]
 [3 0 4]
 [1 7 6]], shape=(3, 3), dtype=int32)
tf.Tensor([2 1 1], shape=(3,), dtype=int64)
tf.Tensor([0 1 0], shape=(3,), dtype=int64)


In [ ]:
# argmax: 넘파이의 argmax와 유사한 함수