In [1]:
import numpy as np

# 1. 다차원 배열의 연산
# 다차원 배열은 사칙 연산을 지원합니다.
a1 = np.array([11,22,33])
a2 = np.array([2,2,2])

print(np.add(a1, a2))
print(np.subtract(a1, a2))    
print(np.multiply(a1, a2))  
print(np.divide(a1, a2))      
print(np.floor_divide(a1, a2))
print(np.mod(a1, a2))         
print(np.power(a1, a2))       
print(np.negative(a1))       

[13 24 35]
[ 9 20 31]
[22 44 66]
[ 5.5 11.  16.5]
[ 5 11 16]
[1 0 1]
[ 121  484 1089]
[-11 -22 -33]


In [2]:
# 넘파이의 다차원 배열은 연산자를 사용하여 직접 계산을 수행할 수 있습니다.
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
print(a1 // a2)
print(a1 % a2)
print(a1 ** a2)
print(-a1)

[13 24 35]
[ 9 20 31]
[22 44 66]
[ 5.5 11.  16.5]
[ 5 11 16]
[1 0 1]
[ 121  484 1089]
[-11 -22 -33]


In [3]:
# 2차원 배열에 대한 연산
arr1 = np.arange(10, 90+1, 10).reshape(3,3)
print(arr1)

arr2 = np.arange(1, 9+1).reshape(3,3)
print(arr2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1%arr2)
print(arr1**arr2)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 9 18 27]
 [36 45 54]
 [63 72 81]]
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[                10                400              27000]
 [           2560000          312500000        46656000000]
 [     8235430000000   1677721600000000 387420489000000000]]


In [5]:
# 행렬곱
a1 = np.array([[1,2,3],
               [4,5,6]])
print(a1.shape)

a2 = np.array([[10,11],
               [20,21],
               [30,31]])
print(a2.shape)

(2, 3)
(3, 2)


In [6]:
print(np.dot(a1, a2))
print(a1.dot(a2))
print(a1@a2)

[[140 146]
 [320 335]]
[[140 146]
 [320 335]]
[[140 146]
 [320 335]]


In [7]:
# 주의! 행렬곱 수행 시, 앞의 배열에 대하여 열의 길이와 뒤의 배열에 대하여 행의 길이가 같지 않으면 오류가 발생합니다.
# a1(2,3) @ a2(3,2) = (2,2)

a1 = np.array([[1,2,3],
               [4,5,6]])
print(a1.shape)

a2 = np.array([[10,11],
               [20,21]])
print(a2.shape)

(2, 3)
(2, 2)


In [8]:
print(a1@a2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [9]:
# 2. 브로드캐스팅
# 형태가 다른 다차원 배열에 대하여 확장을 통해 연산을 수행하는 기능입니다.
arr = np.arange(3)
print(arr + 1)

[1 2 3]


In [10]:
a1 = np.ones((3,3), dtype=np.int)
print(a1.shape)

a2 = np.arange(3)
print(a2.shape)

(3, 3)
(3,)


In [11]:
print(a1 + a2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [12]:
a1 = np.arange(3).reshape(-1,1)
print(a1.shape)

a2 = np.arange(3)
print(a2.shape)

(3, 1)
(3,)


In [13]:
print(a1 + a2)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
# 3. 집계 함수(Aggregate function)
# 집계 함수란 행이나 열 또는 배열 전체로부터 하나의 결과값을 반환하는 함수를 의미합니다.

# 2차원 배열을 기준
# axis=None: 전체 배열을 하나의 배열로 간주하고 집계 함수의 범위를 전체 행렬로 정의한다.
# axis=0: 행을 기준으로 각 행의 동일 인덱스의 요소를 그룹으로 하고 이를 집계 함수의 범위로 정의한다.
# axis=1: 열을 기준으로 각 열의 요소를 그룹으로 하고 이를 집계 함수의 범위로 정의한다.

In [14]:
# 3-1. sum: 지정된 축을 기준으로 총합을 구하는 함수입니다.
arr = np.arange(1, 9+1).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(arr.sum(axis=None), np.sum(arr, axis=None))

45 45


In [16]:
print(arr.sum(), np.sum(arr)) # axis의 기본 값은 None이므로 생략할 수 있습니다.

45 45


In [17]:
print(arr.sum(axis=0), np.sum(arr, axis=0))

[12 15 18] [12 15 18]


In [18]:
print(arr.sum(axis=1), np.sum(arr, axis=1))

[ 6 15 24] [ 6 15 24]


In [19]:
# 3-2. mean: 지정된 축을 기준으로 평균을 구하는 함수입니다.
arr = np.arange(1,9+1).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print(arr.mean(), np.mean(arr2))
print(arr.mean(axis=0), np.mean(arr2, axis=0))
print(arr.mean(axis=1), np.mean(arr2, axis=1))

5.0 5.0
[4. 5. 6.] [4. 5. 6.]
[2. 5. 8.] [2. 5. 8.]


In [21]:
# 3-3. min, max: 지정된 축을 기준으로 최소값과 최대값을 구하는 함수입니다.
arr = np.arange(1, 9+1).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(arr.min(axis=None), np.min(arr, axis=None))
print(arr.min(axis=0), np.min(arr, axis=0))
print(arr.min(axis=1), np.min(arr, axis=1))

1 1
[1 2 3] [1 2 3]
[1 4 7] [1 4 7]


In [23]:
print(arr.max(), np.max(arr))
print(arr.max(axis=0), np.max(arr, axis=0))
print(arr.max(axis=1), np.max(arr, axis=1))

9 9
[7 8 9] [7 8 9]
[3 6 9] [3 6 9]


In [24]:
# 3-4. argmin, argmax: 지정된 축을 기준으로 최소값과 최대값의 인덱스를 구하는 함수입니다.
arr = np.arange(1, 9+1).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(arr.argmin(axis=None), np.argmin(arr, axis=None))
print(arr.argmin(axis=0), np.argmin(arr, axis=0))
print(arr.argmin(axis=1), np.argmin(arr, axis=1))

0 0
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]


In [26]:
print(arr.argmax(), np.argmax(arr))
print(arr.argmax(axis=0), np.argmax(arr, axis=0))
print(arr.argmax(axis=1), np.argmax(arr, axis=1))

8 8
[2 2 2] [2 2 2]
[2 2 2] [2 2 2]
